<a href="https://colab.research.google.com/github/ph2017001/MachineLearning_Wkshp/blob/master/k_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Load Iris Dataset from sklearn and perfrom k-NN Classification and Regression o

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
X,y = load_iris(return_X_y=True)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X[:,:2], y, test_size = 0.30)

In [ ]:
y_test

array([2, 1, 0, 0, 0, 1, 1, 1, 0, 2, 1, 0, 1, 2, 2, 1, 2, 2, 2, 0, 0, 1,
       2, 2, 2, 1, 0, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 1, 2, 2, 0, 2, 2,
       1])

#### Scale the data using Standard Scaler

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print(X_train)

[[-1.00540839 -0.15278253]
 [-0.6354275   1.38550736]
 [-0.88208142  0.72624026]
 [-0.51210053  1.82501876]
 [ 1.83111177 -0.37253823]
 [ 0.7211691   0.28672887]
 [-0.01879268 -0.81204963]
 [ 0.22786125  0.72624026]
 [ 1.09114999 -0.15278253]
 [ 0.47451517 -1.91082813]
 [ 1.09114999  0.50648456]
 [ 0.59784214 -1.69107243]
 [-0.51210053  0.72624026]
 [-0.75875446  0.72624026]
 [-1.12873535  0.06697317]
 [-1.25206231  0.72624026]
 [ 1.58445784 -0.15278253]
 [ 0.35118821 -0.59229393]
 [-0.88208142  0.94599596]
 [-1.49871624  0.28672887]
 [-0.01879268 -0.59229393]
 [-0.51210053  1.38550736]
 [-0.26544661 -0.81204963]
 [ 0.59784214  0.50648456]
 [-0.88208142  1.38550736]
 [ 1.70778481 -0.15278253]
 [ 0.47451517  0.72624026]
 [-0.14211964 -1.03180533]
 [ 2.32441962  1.60526306]
 [ 1.33780392  0.06697317]
 [ 0.96782303 -0.15278253]
 [ 0.96782303 -0.37253823]
 [-1.00540839 -1.69107243]
 [-0.01879268 -0.81204963]
 [-0.26544661 -0.15278253]
 [-1.49871624  0.06697317]
 [ 0.7211691  -0.59229393]
 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print(y_pred)

[2 1 0 0 0 2 1 1 0 1 1 0 1 1 2 1 2 1 2 0 0 2 2 2 2 1 0 0 1 2 2 1 1 1 1 0 0
 1 1 1 2 0 2 2 2]


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
clf_rep = classification_report(y_test, y_pred)
print("Classification Report:",)
print (clf_rep)
acc_scr = accuracy_score(y_test,y_pred)
print("Accuracy:",acc_scr)

Confusion Matrix:
[[12  0  0]
 [ 0 10  5]
 [ 0  8 10]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.56      0.67      0.61        15
           2       0.67      0.56      0.61        18

    accuracy                           0.71        45
   macro avg       0.74      0.74      0.74        45
weighted avg       0.72      0.71      0.71        45

Accuracy: 0.7111111111111111


### k-NN Regressor

In [ ]:
X,y = load_iris(return_X_y=True)

In [ ]:
y = X[:,2]

In [ ]:
X = X[:,:2]

In [ ]:
X[:10]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [ ]:
y[:10]

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5])

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors = 10)
knnr.fit(X, y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                    weights='uniform')

In [ ]:
knnr.predict(X)

array([1.46, 1.45, 1.51, 1.42, 1.46, 1.56, 1.46, 1.46, 1.37, 1.46, 1.52,
       1.52, 1.48, 1.37, 1.46, 1.52, 1.56, 1.46, 1.48, 1.49, 1.5 , 1.49,
       1.46, 1.44, 1.52, 1.47, 1.46, 1.46, 1.52, 1.51, 1.48, 1.5 , 1.54,
       1.49, 1.46, 1.49, 1.49, 1.47, 1.37, 1.48, 1.46, 2.41, 1.39, 1.46,
       1.49, 1.48, 1.49, 1.49, 1.53, 1.48, 5.49, 5.32, 5.19, 4.05, 5.16,
       4.52, 5.12, 3.17, 5.02, 3.64, 3.44, 4.6 , 4.59, 4.69, 4.28, 5.21,
       4.37, 4.36, 4.87, 4.05, 4.7 , 4.72, 5.01, 4.72, 5.19, 5.04, 5.02,
       5.07, 4.66, 4.33, 4.05, 4.05, 4.36, 4.68, 4.22, 4.95, 5.21, 4.94,
       4.37, 4.14, 4.19, 4.58, 4.44, 3.43, 4.21, 4.36, 4.43, 4.72, 3.79,
       4.52, 5.12, 4.36, 5.53, 5.02, 5.02, 6.11, 2.72, 5.96, 5.06, 5.62,
       5.3 , 5.07, 5.17, 4.23, 4.5 , 5.32, 5.02, 6.04, 6.11, 4.59, 5.34,
       4.36, 6.11, 5.11, 5.33, 5.59, 4.93, 4.58, 5.04, 5.59, 6.11, 6.14,
       5.04, 5.02, 4.88, 6.11, 5.23, 5.16, 4.63, 5.19, 5.21, 5.19, 4.36,
       5.31, 5.33, 5.07, 5.01, 5.02, 5.14, 4.6 ])

In [ ]:
knnr.score(X,y)

0.9449465827197909

In [ ]:
import numpy as np

In [ ]:
print ("The MSE is:",format(np.power(y-knnr.predict(X),2).mean()))

The MSE is: 0.17041799999999996
