<a href="https://colab.research.google.com/github/ph2017001/MachineLearning_Wkshp/blob/master/k_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Load Iris Dataset from sklearn and perfrom k-NN Classification and Regression o

In [1]:
from sklearn.datasets import load_iris

In [2]:
X,y = load_iris(return_X_y=True)

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X[:,:2], y, test_size = 0.30)

#### Scale the data using Standard Scaler

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
print(X_train)

[[-0.51090949  1.4706548 ]
 [-1.73290257 -0.3327759 ]
 [ 0.71108359 -0.55820474]
 [-0.02211226  2.14694131]
 [-0.87750741  0.56893945]
 [ 1.68867806 -0.10734707]
 [-1.12190603 -0.10734707]
 [ 1.07768152 -0.10734707]
 [ 1.07768152  0.11808177]
 [-0.7553081   1.01979712]
 [-0.38871018  2.59779899]
 [-0.99970672  0.79436829]
 [ 1.81087737 -0.3327759 ]
 [ 0.10008705 -0.10734707]
 [ 0.34448567 -1.00906242]
 [-0.99970672 -2.36163544]
 [-0.02211226 -0.78363358]
 [-0.7553081   2.37237015]
 [ 0.58888429  0.79436829]
 [ 0.58888429 -1.23449125]
 [-0.14431156 -1.00906242]
 [ 0.22228636 -0.3327759 ]
 [ 1.07768152 -0.10734707]
 [-0.99970672  1.01979712]
 [-0.14431156 -0.55820474]
 [-1.24410534 -0.10734707]
 [ 1.19988083 -0.55820474]
 [-0.14431156 -1.23449125]
 [ 0.58888429 -1.23449125]
 [ 0.95548221 -0.3327759 ]
 [-1.12190603 -1.23449125]
 [-0.87750741  1.69608364]
 [ 0.58888429 -0.3327759 ]
 [ 0.71108359  0.34351061]
 [-0.99970672  0.79436829]
 [-1.24410534 -0.10734707]
 [-0.99970672  1.01979712]
 

In [21]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [22]:
y_pred = classifier.predict(X_test)

In [23]:
print(y_pred)

[2 0 1 1 1 0 1 1 2 1 2 1 1 2 0 0 1 1 2 0 1 2 2 2 2 0 0 1 0 0 1 2 0 0 2 2 1
 1 1 0 0 0 1 1 2]


In [24]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
clf_rep = classification_report(y_test, y_pred)
print("Classification Report:",)
print (clf_rep)
acc_scr = accuracy_score(y_test,y_pred)
print("Accuracy:",acc_scr)

Confusion Matrix:
[[14  1  0]
 [ 0 11  4]
 [ 0  6  9]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.61      0.73      0.67        15
           2       0.69      0.60      0.64        15

    accuracy                           0.76        45
   macro avg       0.77      0.76      0.76        45
weighted avg       0.77      0.76      0.76        45

Accuracy: 0.7555555555555555


### k-NN Regressor

In [28]:
X,y = load_iris(return_X_y=True)

In [29]:
y = X[:,2]

In [30]:
X = X[:,:2]

In [32]:
X[:10]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [33]:
y[:10]

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5])

In [34]:
from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors = 10)
knnr.fit(X, y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                    weights='uniform')

In [35]:
knnr.predict(X)

array([1.46, 1.45, 1.51, 1.42, 1.46, 1.56, 1.46, 1.46, 1.37, 1.46, 1.52,
       1.52, 1.48, 1.37, 1.46, 1.52, 1.56, 1.46, 1.48, 1.49, 1.5 , 1.49,
       1.46, 1.44, 1.52, 1.47, 1.46, 1.46, 1.52, 1.51, 1.48, 1.5 , 1.54,
       1.49, 1.46, 1.49, 1.49, 1.47, 1.37, 1.48, 1.46, 2.41, 1.39, 1.46,
       1.49, 1.48, 1.49, 1.49, 1.53, 1.48, 5.49, 5.32, 5.19, 4.05, 5.16,
       4.52, 5.12, 3.17, 5.02, 3.64, 3.44, 4.6 , 4.59, 4.69, 4.28, 5.21,
       4.37, 4.36, 4.87, 4.05, 4.7 , 4.72, 5.01, 4.72, 5.19, 5.04, 5.02,
       5.07, 4.66, 4.33, 4.05, 4.05, 4.36, 4.68, 4.22, 4.95, 5.21, 4.94,
       4.37, 4.14, 4.19, 4.58, 4.44, 3.43, 4.21, 4.36, 4.43, 4.72, 3.79,
       4.52, 5.12, 4.36, 5.53, 5.02, 5.02, 6.11, 2.72, 5.96, 5.06, 5.62,
       5.3 , 5.07, 5.17, 4.23, 4.5 , 5.32, 5.02, 6.04, 6.11, 4.59, 5.34,
       4.36, 6.11, 5.11, 5.33, 5.59, 4.93, 4.58, 5.04, 5.59, 6.11, 6.14,
       5.04, 5.02, 4.88, 6.11, 5.23, 5.16, 4.63, 5.19, 5.21, 5.19, 4.36,
       5.31, 5.33, 5.07, 5.01, 5.02, 5.14, 4.6 ])

In [36]:
knnr.score(X,y)

0.9449465827197909

In [38]:
import numpy as np

In [39]:
print ("The MSE is:",format(np.power(y-knnr.predict(X),2).mean()))

The MSE is: 0.17041799999999996
