<a href="https://colab.research.google.com/github/ph2017001/MachineLearning_Wkshp/blob/master/Simple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import Packages

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression 

#### Prepare Data

In [ ]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [ ]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [ ]:
y

array([ 5, 20, 14, 32, 22, 38])

#### Instantiate Model Object

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x, y)
# or LinearRegression().fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.intercept_

5.633333333333329

In [ ]:
model.coef_

array([0.54])

In [ ]:
r_square = model.score(x, y)

In [ ]:
print(r_square)

0.7158756137479542


In [ ]:
y_pred = model.predict(x)

In [ ]:
print(y_pred)

[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [ ]:
model.predict(np.array([10,70,100]).reshape(-1, 1))

array([11.03333333, 43.43333333, 59.63333333])

## For any Linear Regression
Instantiate a model 
Call Fit 
To get prediction : Call "predict" , passing the "input" in proper
To get the score : Call the ".score" function of the model.

# Activity : 
## Try Polynomial Regression on the same data
#### *Hint: from sklearn.preprocessing import PolynomialFeatures*